# Generated by Django 5.1.7 on 2025-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('food_items', models.TextField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('discount_applied', models.FloatField(default=0)),
                ('payment_method', models.CharField(max_length=20)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
